<?php

/* layout/page.twig */
class __TwigTemplate_50e4884a050ea9ee7f18ebdf48097976 extends Twig_Template
{
    public function __construct(Twig_Environment $env)
    {
        parent::__construct($env);

        $this->parent = false;

        $this->blocks = array(
            'title' => array($this, 'block_title'),
            'current_class' => array($this, 'block_current_class'),
            'current_namespace' => array($this, 'block_current_namespace'),
            'content' => array($this, 'block_content'),
        );
    }

    protected function doDisplay(array $context, array $blocks = array())
    {
        // line 1
        echo "---
layout: api
title: \"";
        // line 3
        $this->displayBlock('title', $context, $blocks);
        echo "\"
footer: 'Generated by <a href=\"https://github.com/fabpot/Sami\" target=\"_top\">Sami, the API Documentation Generator</a>.'
current: api
current_class: \"";
        // line 6
        $this->displayBlock('current_class', $context, $blocks);
        echo "\"
current_namespace: \"";
        // line 7
        $this->displayBlock('current_namespace', $context, $blocks);
        echo "\"
---

";
        // line 10
        $this->displayBlock('content', $context, $blocks);
    }

    // line 3
    public function block_title($context, array $blocks = array())
    {
        echo "";
    }

    // line 6
    public function block_current_class($context, array $blocks = array())
    {
        echo "";
    }

    // line 7
    public function block_current_namespace($context, array $blocks = array())
    {
        echo "";
    }

    // line 10
    public function block_content($context, array $blocks = array())
    {
        echo "";
    }

    public function getTemplateName()
    {
        return "layout/page.twig";
    }

    public function getDebugInfo()
    {
        return array (  63 => 10,  57 => 7,  51 => 6,  45 => 3,  35 => 7,  31 => 6,  25 => 3,  21 => 1,  779 => 7,  776 => 6,  765 => 5,  759 => 241,  753 => 238,  749 => 236,  747 => 235,  744 => 234,  738 => 231,  734 => 229,  732 => 228,  729 => 227,  723 => 224,  719 => 222,  717 => 221,  714 => 220,  708 => 217,  704 => 215,  702 => 214,  697 => 212,  693 => 211,  687 => 208,  682 => 207,  679 => 206,  660 => 202,  642 => 201,  639 => 200,  634 => 197,  618 => 194,  613 => 192,  611 => 191,  606 => 188,  598 => 187,  591 => 184,  587 => 182,  585 => 181,  581 => 179,  564 => 178,  561 => 177,  558 => 176,  553 => 173,  544 => 170,  540 => 169,  534 => 167,  529 => 166,  525 => 165,  521 => 164,  518 => 163,  514 => 162,  511 => 161,  508 => 160,  503 => 157,  493 => 153,  489 => 152,  484 => 150,  481 => 149,  477 => 148,  474 => 147,  471 => 146,  466 => 143,  457 => 140,  453 => 139,  450 => 138,  446 => 137,  443 => 136,  440 => 135,  435 => 132,  426 => 129,  422 => 128,  419 => 127,  415 => 126,  412 => 125,  409 => 124,  401 => 119,  397 => 118,  393 => 116,  390 => 115,  385 => 112,  378 => 110,  372 => 109,  364 => 108,  358 => 107,  355 => 106,  351 => 105,  348 => 104,  345 => 103,  341 => 100,  339 => 99,  336 => 98,  330 => 95,  325 => 94,  320 => 93,  315 => 92,  310 => 91,  305 => 90,  300 => 89,  296 => 88,  293 => 87,  274 => 82,  272 => 81,  255 => 80,  252 => 79,  250 => 78,  246 => 76,  244 => 75,  240 => 74,  234 => 73,  230 => 72,  227 => 71,  220 => 67,  213 => 63,  209 => 61,  207 => 60,  204 => 59,  199 => 57,  193 => 55,  191 => 54,  188 => 53,  183 => 51,  177 => 49,  175 => 48,  170 => 45,  166 => 43,  161 => 42,  158 => 41,  140 => 39,  123 => 38,  119 => 36,  117 => 35,  114 => 34,  108 => 32,  105 => 31,  101 => 30,  97 => 29,  93 => 28,  90 => 27,  88 => 26,  82 => 23,  77 => 21,  69 => 20,  64 => 17,  61 => 16,  53 => 14,  47 => 12,  41 => 10,  36 => 3,);
    }
}
